name: CI - Build e teste da Imagem DOcker

on: 
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Baixar o codigo do repo
      uses: actions/checkout@v3

    - name: 2. Construir a imagem do Docker
      uses: docker build -t app-teste:local .

    - name: 3. Executar o container para validar
      uses: docker run --rm app-teste:local
      